title: openSUSE Release Tools
description: |
  News about openSUSE release tool improvements and process changes. The release
  team can be contacted via opensuse-releaseteam@opensuse.org mailing list or
  in freenode.net IRC in the opensuse-factory channel.

author: Jimmy Berry
email: jberry@suse.com
github_username: openSUSE/osc-plugin-factory

url: http://release-tools.opensuse.org
baseurl: ""

theme: minima
minima:
  date_format: "%Y-%m-%d"

google_analytics: true

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - CNAME
  - LICENSE
  - README.md
